name: kubernetes-worker
base: core18
version: '0.0.1'
summary: A complete Kubernetes worker
description: |
  A fully functional Kubernetes worker in a snap.  This includes kubelet,
  kube-proxy, kubectl, flanneld, containerd.

grade: devel
confinement: devmode

plugs:
  docker-privileged:
    interface: docker-support
    privileged-containers: true
  k8s-kubelet:
    flavor: kubelet
    interface: kubernetes-support
  k8s-kubeproxy:
    flavor: kubeproxy
    interface: kubernetes-support
  dot-kube:
    interface: personal-files
    write:
    - $HOME/.kube

# If hooks are used, be sure they don't inherit the top-level plugs
#hooks. Eg:
#  configure:
#    plugs:
#    - network

apps:
  containerd:
    command: containerd.wrapper
    daemon: simple
    plugs:
    - docker-privileged
    - docker-support
    - firewall-control
    - kernel-module-control
    - network-bind
    - network-control

  kubelet:
    command: kubelet.wrapper
    daemon: simple
    plugs:
    - firewall-control
    - hardware-observe
    - k8s-kubelet
    - mount-observe
    - network-bind
    - network-control
    - process-control
    - system-observe

  kube-proxy:
    command: kube-proxy
    daemon: simple
    plugs:
    - firewall-control
    - k8s-kubeproxy
    - kernel-module-control
    - kernel-module-observe
    - mount-observe
    - network-bind
    - network-observe
    - system-observe

  ctr:
    command: ctr.wrapper
    plugs:
    - docker-privileged
    - docker-support
    - firewall-control
    - network-bind
    - network-control

  kubectl:
    command: kubectl.wrapper
    plugs:
    - dot-kube
    - firewall-control
    - hardware-observe
    - home
    - k8s-kubelet
    - mount-observe
    - network-bind
    - network-control
    - process-control
    - system-observe

parts:
  setup:
    after:
      - artifacts
      - wrappers
    source: build/
    plugin: dump

  wrappers:
    source: wrappers/
    plugin: dump
    organize:
      containerd.wrapper: bin/containerd.wrapper
      ctr.wrapper: bin/ctr.wrapper
      kubectl.wrapper: bin/kubectl.wrapper
      kubelet.wrapper: bin/kubelet.wrapper

  artifacts:
    source: artifacts/
    plugin: dump

  kubernetes:
    after:
      - setup
      - containerd
    plugin: nil
    build-snaps:
      - go/1.12/stable
    build-packages:
    - git
    - gcc
    - make
    - pkg-config
    override-build: |
      set -eu
      . ../../../parts/setup/build/common.sh
      . ../../../parts/setup/build/lock.sh

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin

      go get -d k8s.io/kubernetes || true
      (
        cd $GOPATH/src/k8s.io/kubernetes
        git checkout ${KUBERNETES_COMMIT}
        make
      )
      cp $GOPATH/src/k8s.io/kubernetes/_output/local/go/bin/* $SNAPCRAFT_PART_INSTALL/bin/

  containerd:
    after:
      - setup
    plugin: nil
    build-snaps:
      - go/1.12/stable
    build-packages:
    - git
    - gcc
    - make
    - pkg-config
    - btrfs-tools
    - libseccomp-dev
    override-build: |
      set -eu
      . ../../../parts/setup/build/common.sh
      . ../../../parts/setup/build/lock.sh

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin

      #  Build Containerd
      go get github.com/containerd/containerd
      (
        cd $GOPATH/src/github.com/containerd/containerd
        git checkout ${CONTAINERD_COMMIT}
        make
      )
      cp $GOPATH/src/github.com/containerd/containerd/bin/* $SNAPCRAFT_PART_INSTALL/bin/
      rm $SNAPCRAFT_PART_INSTALL/bin/containerd-stress

      # Build Runc
      go get github.com/opencontainers/runc
      (
        cd $GOPATH/src/github.com/opencontainers/runc
        git checkout ${RUNC_COMMIT}
        make BUILDTAGS='seccomp apparmor'
      )
      cp $GOPATH/src/github.com/opencontainers/runc/runc $SNAPCRAFT_PART_INSTALL/bin/

    organize:
      go/src/github.com/containerd/containerd/bin/*: bin/
      go/src/github.com/opencontainers/runc/runc: bin/runc
      containerd/install/bin/*: bin/
    stage-packages:
    - libnss-myhostname
    - libnss-resolve
    - libnss-mymachines
    - conntrack
    - aufs-tools
    - gawk
    - sed
    - socat
    - grep
    - libssl1.0.0
    - coreutils
    - hostname
    - diffutils
    stage:
    - -sbin/xtables-multi
    - -sbin/iptables*
    - -lib/xtables
